### ISSUE TITLE
npm i fails

### ISSUE THREAD

**Issue by zxdong262** [Tyriar/node-pty#149]
```
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/zxd/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-37-generic
gyp ERR! command "/home/zxd/.nvm/versions/node/v8.7.0/bin/node" "/home/zxd/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/zxd/dev/electerm/node_modules/node-pty
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```
I do searched a lot, no solution works for me.
ubuntu 16.04.3x64

**Comment by zxdong262** [comment]
use node 8.5 fixed it.

**Comment by zxdong262** [comment]
no, it is proxy issue, do not use proxy, it will be fine
