### ISSUE TITLE
Won't load DLL with newest Electron (1.7.11)

### ISSUE THREAD

**Issue by darekg11** [Tyriar/node-pty#174]
Hey guys, I wanted to use this amazing library in conjucton with `xterm.js` and Electron 1.7.11 but I am pulling my hairs from head like crazy yesterday and today because I am keeping getting following stacktrace:  
```
Uncaught Error:  A dynamic link library (DLL) initialization routine failed.
\\?\D:\Programowanie\Projekty\node-pty\examples\electron\node_modules\node-pty\build\Release\pty.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Programowanie\Projekty\node-pty\examples\electron\node_modules\node-pty\lib\windowsPtyAgent.js:9:11)
    at Object.<anonymous> (D:\Programowanie\Projekty\node-pty\examples\electron\node_modules\node-pty\lib\windowsPtyAgent.js:149:3)
```  

The weird thing is that I can launch demo Electron app without problems.
I have modified `npm_install.bat` from example directory to following form:  
```@echo off
setlocal
set npm_config_disturl="https://atom.io/download/electron"
set npm_config_target=1.7.11
set npm_config_runtime="electron"
set npm_config_cache=~\.npm-electron
npm i
endlocal
```
and ran ```npm rebuild```

Node version: `8.5.0`

**Comment by darekg11** [comment]
I do not understand why but removing `node_modules`, executing `npm_install.sh` resolved that.

**Comment by Tyriar** [comment]
You likely had some modules hanging around from the previous version.

**Comment by mohankumargupta** [comment]
I was having the same difficulty, now have a reliable solution for Windows 10.

package.json(incomplete)
---------------
{
  "scripts": {
    "start": "electron .",
    "rebuild": "./node_modules/.bin/electron-rebuild"
  },
  "devDependencies": {
    "electron": "^1.8.3",
    "electron-rebuild": "^1.7.3"
  },
  "dependencies": {
    "node-pty": "^0.7.4",
    "xterm": "^3.2.0"
  }
}

-----
Then run:

npm install
npm rebuild

**Comment by Tyriar** [comment]
@mohankumargupta you need to use electron's v8 to build, see https://github.com/Tyriar/node-pty/blob/master/examples/electron/npm_install.bat
