### ISSUE TITLE
Is resize broken?

### ISSUE THREAD

**Issue by ioquatix** [Tyriar/node-pty#37]
I didn't change any code, when moving from `pty.js` to `node-pty`, but have the following issue:

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.3
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package, v2.1.0

### Stack Trace

Uncaught Error: Usage: pty.resize(fd, cols, rows)

```
At /Users/samuel/.atom/packages/script-runner/node_modules/node-pty/lib/unixTerminal.js:148

Error: Usage: pty.resize(fd, cols, rows)
    at Error (native)
    at UnixTerminal.resize (/Users/samuel/.atom/packages/script-runner/node_modules/node-pty/lib/unixTerminal.js:148:13)
    at /Users/samuel/.atom/packages/script-runner/lib/script-runner-process.coffee:110:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/User/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/User/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Terminal.<anonymous> (/Users/samuel/.atom/packages/script-runner/lib/script-runner-view.coffee:96:16)
    at Terminal.EventEmitter.emit (/Users/samuel/.atom/packages/script-runner/node_modules/xterm/lib/EventEmitter.js:45:16)
    at Terminal.resize (/Users/samuel/.atom/packages/script-runner/node_modules/xterm/lib/xterm.js:2654:10)
    at Object.exports.fit (/Users/samuel/.atom/packages/script-runner/node_modules/xterm/lib/addons/fit/fit.js:49:14)
    at Terminal.Xterm.fit (/Users/samuel/.atom/packages/script-runner/node_modules/xterm/lib/addons/fit/fit.js:55:24)
    at ScriptRunnerView.module.exports.ScriptRunnerView.outputResized (/Users/samuel/.atom/packages/script-runner/lib/script-runner-view.coffee:73:13)
    at /Users/samuel/.atom/packages/script-runner/lib/script-runner-view.coffee:32:56
    at callListenerProxy (/Users/samuel/.atom/packages/script-runner/node_modules/element-resize-detector/src/element-resize-detector.js:153:17)
    at utils.forEach (/Users/samuel/.atom/packages/script-runner/node_modules/element-resize-detector/src/collection-utils.js:14:22)
    at onResizeCallback (/Users/samuel/.atom/packages/script-runner/node_modules/element-resize-detector/src/element-resize-detector.js:152:13)
    at /Users/samuel/.atom/packages/script-runner/node_modules/element-resize-detector/src/detection-strategy/scroll.js:491:21
    at utils.forEach (/Users/samuel/.atom/packages/script-runner/node_modules/element-resize-detector/src/collection-utils.js:14:22)
    at notifyListenersIfNeeded (/Users/samuel/.atom/packages/script-runner/node_modules/element-resize-detector/src/detection-strategy/scroll.js:490:17)
    at /Users/samuel/.atom/packages/script-runner/node_modules/element-resize-detector/src/detection-strategy/scroll.js:458:25
    at Object.process (/Users/samuel/.atom/packages/script-runner/node_modules/batch-processor/src/batch-processor.js:124:17)
    at processBatch (/Users/samuel/.atom/packages/script-runner/node_modules/batch-processor/src/batch-processor.js:37:29)
```

**Comment by ioquatix** [comment]
Here is the code interacting with `node-pty`:

```coffee script
  spawn: (args, cwd, env, callback) ->
    # Spawn the child process:
    console.log("ScriptRunner.spawn", args[0], args.slice(1), cwd, env)
    
    @pty = PTY.open()
    @child = ChildProcess.spawn(args[0], args.slice(1), cwd: cwd, env: env, stdio: [@pty.slave, @pty.slave, @pty.slave], detached: true)
    # @pty.slave.end()
    
    @startTime = new Date
    
    # Update the status (*Shellwords.join doesn't exist yet):
    @view.setHeader('Running: ' + args.join(' ') + ' (pgid ' + @child.pid + ')')
    
    @view.on 'data', (data) =>
      console.log('data', data)
      if @pty?
        @pty.master.write(data)
    
    @view.on 'resize', (cols, rows) =>
      if @pty?
        @pty.resize(cols, rows)
    
    @view.focus()
    
    # Handle various events relating to the child process:
    @pty.master.on 'data', (data) =>
      if @view?
        @view.append(data, 'stdout')
    
    @child.on 'exit', (code, signal) =>
      @child = null
      @pty.destroy()
      @pty = null
      
      console.log('child', 'exit', code, signal)
      @endTime = new Date
      if @view
        duration = ' after ' + ((@endTime - @startTime) / 1000) + ' seconds'
        if signal
          @view.setFooter('Exited with signal ' + signal + duration)
        else
          # Sometimes code seems to be null too, not sure why, perhaps a bug in node.
          code ||= 0
          @view.setFooter('Exited with status ' + code + duration)
```

**Comment by ioquatix** [comment]
Okay found the bug is on my end.
